### ISSUE TITLE
Spree wholesale breaks with version 1.5.0 of CanCan

### ISSUE THREAD

**Issue by lukef** [citrus/spree_wholesale#1]
Using version 1.5 of cancan with spree causes the following error: 
undefined local variable or method `can_definitions'

According to the CanCan site: 
CanDefinition was renamed to Rule, so the method is now called rules in 1.5.0.

I don't know if this is a spree issue or on the plugin side

**Comment by citrus** [comment]
Thanks for letting me know. I'll take a look and work on a fix this week. What Ruby and Spree versions are you running?

Thanks,

-Spencer
