### ISSUE TITLE
Spork or no Spork?

### ISSUE THREAD

**Issue by citrus** [citrus/spree_wholesale#10]
Is anyone opposed to me removing the spork dependency on spree_wholesale?

cc/ @tavon @sanarothe

**Comment by ieve-rothe** [comment]
Nope, not using spork.

Thanks,

Cameron

**Comment by citrus** [comment]
Cool, then unless @tavon can convince me otherwise I'm removing it

**Comment by tavon** [comment]
+1 No objections.

**Comment by citrus** [comment]
Done! Spork removed in 315cec47237ae9bf64c1a90e20db486d4d8fcdc7

Got rid of database cleaner too :)
