### ISSUE TITLE
Issues with edit/update

### ISSUE THREAD

**Issue by tavon** [citrus/spree_wholesale#11]
SpreeWholesale::WholesalerController feels really brittle and needs to be refactored.

Currently, only new/create and edit/update is testing only for admin::wholesalers_controller.  Adding a new wholesaler works well, but when I try to update a wholesaler, it fails pretty consistently.  I believe the issues is with the Address models failing to update & associate with the Wholesaler object in #update... 

We definitely need to add some more tests around the wholesalers controllers and should refactor it as well.

**Comment by citrus** [comment]
I completely agree, the wholesaler controller lib is a bit finicky and needs refactoring and more testing. I'll see if I can work on it a bit tonight.

**Comment by tavon** [comment]
I've made a pull request (#14) to solve this issue.
