### ISSUE TITLE
Dependancy Failure

### ISSUE THREAD

**Issue by samhamilton** [citrus/spree_wholesale#16]
When trying to install with Spree 1.0.3 I get the following error: 

$ bundle install
Updating git://github.com/citrus/spree_wholesale
Fetching gem metadata from https://rubygems.org/........
Fetching gem metadata from https://rubygems.org/..
Bundler could not find compatible versions for gem "spree_auth":
  In snapshot (Gemfile.lock):
    spree_auth (1.0.3)

  In Gemfile:
    spree_wholesale (>= 0) ruby depends on
      spree_auth (~> 0.70.0) ruby

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.

I used the following in my Gemfile:
gem 'spree_wholesale', :git => 'git://github.com/citrus/spree_wholesale', :branch => 'master'

Thanks
Sam

**Comment by rozhok** [comment]
Hi, here's commit you can use to solve this:
https://github.com/kieranj/spree_wholesale/commit/da2f9477a79fc8e0033bfaeb45a9e7f9daea5e59
