### ISSUE TITLE
Treat Wholesaler more like Admin?

### ISSUE THREAD

**Issue by patrickmcelwee** [citrus/spree_wholesale#18]
Could we treat the wholesaler role more like the admin role? It seems to me that, while it would take a good deal of refactoring, it would also simplify the code and the behavior. It would:
- solve the issue of not being able to designate a current user as wholesaler
- otherwise play nicely and easily with Spree user management
- allow an intuitive way to "delete" a wholesaler from the wholesale list without destroying the user and address records (this could be done in other ways ... like creating a "deleted_at" in the wholesaler model ... but this would seem to work better and was what got me thinking about this)

Are there reasons not to do this and to maintain wholesaler as a separate model?

**Comment by citrus** [comment]
I like it :) 

I'm no longer doing Spree work so if you'd like to implement these features feel free!

-Spencer

**Comment by patrickmcelwee** [comment]
Yes, I may do that sometime over the next month or two ... I am going to be focusing on the wholesale part of our site quite a bit.

Sorry to lose you on Spree! I have benefited from several of your extensions.
