### ISSUE TITLE
Adding products to wholesaler

### ISSUE THREAD

**Issue by youthmonument** [citrus/spree_wholesale#2]
Hi,

I have posted this question up on the Spree extension page and on the google group with no reply.

I need to default the wholesaler to show all products instead of having to add every product individually. How do I go about doing so?

Please reply because this is a major issue that needs to be addressed.

**Comment by citrus** [comment]
Hi,

Sorry for not getting back to you sooner.. I don't get alerts from the extension page and don't check it very often. 

I'm not sure if I understand what you need. Can you be a bit more specific? 

Thanks!

-Spencer

**Comment by youthmonument** [comment]
Spencer,

The issue we run into is when we set up a wholesaler on our site, we have to manually add every-single variant so that they appear when the wholesaler logs in. 

We have 400 variants and to add every one individually would take forever to do. How can we default it to show all variants when the wholesaler is created? 

If we are able to default all the variants to appear it will take us less time to go through and delete what ever we do not want them to see.

I hope that makes sense.

If you have any other questions let know.

Regards,

Joseph Munayyer
Youth Monument Clothing, Inc.
Director of Operations/ Sales
225 West 38th Street
Los Angeles, CA 90037-1405
323.521.1397 ext. 15 (Office)
818.471.9897 (Cell)
www.YouthMonument.com

**Comment by citrus** [comment]
From what I understand, you're trying to set the wholesale price on each variant, right?

This can be easily achieved by using a rake task similar to `rake spree_wholesale:assume_wholesale_prices`. 

Here's an example:

``` ruby
desc "Sets wholesale price for each variant"
task :set_wholesale_prices => :environment do      
  Variant.all.each do |variant|

    # your wholesale price formula would go here
    price = variant.price * 0.66

    ActiveRecord::Base.connection.execute("UPDATE variants SET wholesale_price = #{price} WHERE id = #{variant.id}")

  end
end
```

Hope that helps!

-Spencer

**Comment by youthmonument** [comment]
No we are trying to default all the variants to show up by default instead of adding all the variants for the wholesaler separately.

If you are in the US can you give me a call so I can better explain whats going on because trying to explain via email is very difficult.

Regards,

Joseph Munayyer
Youth Monument Clothing, Inc.
Director of Operations/ Sales
240 West 37th Place
Los Angeles, CA 90007
818.471.9897 (Cell)
www.YouthMonument.com
