### ISSUE TITLE
pay later option redirects back to checkout start

### ISSUE THREAD

**Issue by angileri** [citrus/spree_wholesale#7]
Hi,  thanks for this.  I am having an issue with checking out wholesaler and using pay later.  When continuing should bring you to the summary page but will go back to the cart.  The order does actually  go through.  What I am finding that at this point of failure the customer needs to log out and then back in to process or even checkout again.  so maybe has to do with session not getting closed.  i am using 0.60.1 version.  

Thanks

**Comment by tavon** [comment]
#15 resolves this issue and should be closed although it only applies to 0.70.x.  I believe the code should work with 0.60.x as well.

The issue was that the state_machine states were not stepped through with the appropriate callbacks and therefore the orders were not cleanly completed.

**Comment by citrus** [comment]
Awesome thanks for checking this out @tavon

**Comment by angileri** [comment]
great i will try on 0.60.4
